export const nodeTypeList = [
  { id: 0, name: 'Undefined' },
  { id: 1, name: 'Node' },
  { id: 2, name: 'API' },
  { id: 3, name: 'ETL' },
  { id: 4, name: 'Miner' },
  { id: 5, name: 'Validator' },
  { id: 6, name: 'Oracle' },
  { id: 7, name: 'Relay' },
];

export const nodeStatusList = [
  { id: 0, name: 'Undefined' },
  { id: 1, name: 'Broadcasting' },
  { id: 2, name: 'Cancelled' },
  { id: 3, name: 'Delegating' },
  { id: 4, name: 'Delinquent' },
  { id: 5, name: 'Disabled' },
  { id: 6, name: 'Earning' },
  { id: 7, name: 'Electing' },
  { id: 8, name: 'Elected' },
  { id: 9, name: 'Exporting' },
  { id: 10, name: 'Ingesting' },
  { id: 11, name: 'Mining' },
  { id: 12, name: 'Minting' },
  { id: 13, name: 'Processing' },
  { id: 14, name: 'Relaying' },
  { id: 15, name: 'Removed' },
  { id: 16, name: 'Removing' },
];

export const hostStatusList = [
  { id: 0, name: 'Undefined' },
  { id: 1, name: 'Creating' },
  { id: 2, name: 'Running' },
  { id: 3, name: 'Starting' },
  { id: 4, name: 'Stopping' },
  { id: 5, name: 'Stopped' },
  { id: 6, name: 'Upgrading' },
  { id: 7, name: 'Upgraded' },
  { id: 8, name: 'Deleting' },
  { id: 9, name: 'Deleted' },
  { id: 10, name: 'Installing' },
  { id: 11, name: 'Snaphotting' },
];
