export const nodeTypeList = [
  { id: 4, name: 'API' },
  { id: 8, name: 'Beacon' },
  { id: 2, name: 'ETL' },
  { id: 7, name: 'Execution' },
  { id: 11, name: 'Full Node' },
  { id: 12, name: 'Light Node' },
  { id: 9, name: 'MEV Boost' },
  { id: 1, name: 'Miner' },
  { id: 10, name: 'Node' },
  { id: 5, name: 'Oracle' },
  { id: 6, name: 'Relay' },
  { id: 3, name: 'Validator' },
];

/*
Unknown = 0,
    Miner = 1,
    Etl = 2,
    Validator = 3,
    Api = 4,
    Oracle = 5,
    Relay = 6,
    Execution = 7,
    Beacon = 8,
    MevBoost = 9,
    Node = 10,
    FullNode = 11,
    LightNode = 12,
 */
export const blockchainList = [
  { value: '1', label: 'Algorand' },
  { value: '2', label: 'Aptos' },
  { value: '3', label: 'Cosmos' },
  { value: '4', label: 'Ethereum' },
  { value: '5', label: 'Helium' },
  { value: '6', label: 'Lightning' },
  { value: '7', label: 'Near' },
  { value: '8', label: 'Pocket' },
  { value: '9', label: 'Polygon' },
  { value: '10', label: 'Solana' },
];

export const nodeStatusList = [
  { id: 2, name: 'Broadcasting' },
  { id: 3, name: 'Cancelled' },
  { id: 4, name: 'Delegating' },
  { id: 5, name: 'Delinquent' },
  { id: 6, name: 'Disabled' },
  { id: 7, name: 'Earning' },
  { id: 8, name: 'Electing' },
  { id: 9, name: 'Elected' },
  { id: 10, name: 'Exporting' },
  { id: 11, name: 'Ingesting' },
  { id: 12, name: 'Mining' },
  { id: 13, name: 'Minting' },
  { id: 14, name: 'Processing' },
  { id: 14, name: 'Relaying' },
  { id: 15, name: 'Removed' },
  { id: 16, name: 'Removing' },
  { id: 0, name: 'Undefined' },
];

export const hostStatusList = [
  { id: 0, name: 'Undefined' },
  { id: 1, name: 'Creating' },
  { id: 2, name: 'Running' },
  { id: 3, name: 'Starting' },
  { id: 4, name: 'Stopping' },
  { id: 5, name: 'Stopped' },
  { id: 6, name: 'Upgrading' },
  { id: 7, name: 'Upgraded' },
  { id: 8, name: 'Deleting' },
  { id: 9, name: 'Deleted' },
  { id: 10, name: 'Installing' },
  { id: 11, name: 'Snaphotting' },
];

export const nodeTypeProps = {
  number: 'number',
  text: 'string',
  boolean: 'boolean',
  fileUpload: 'file-upload',
  hostSelector: 'host-selector',
  nodeSelector: 'node-selector',
};
