name: Web Build and Push

on:
  push:
    branches: [develop]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: 'https://api.nodexeus.io'
      NEXT_PUBLIC_MQTT_USERNAME: 'nodexeus'
      NEXT_PUBLIC_MQTT_PASSWORD: ${{ secrets.MQTT_PASSWORD }}
      NEXT_PUBLIC_MQTT_URL: 'wss://mqtt.nodexeus.io:8084/mqtt'
      NEXT_PUBLIC_VERCEL_ENV: 'production'
      NEXT_PUBLIC_LOADING_DURATION: '200'
      NEXT_PUBLIC_STRIPE_KEY: ${{ secrets.STRIPE_KEY }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        env:
          NODE_ENV: production
          NEXT_PUBLIC_API_URL: 'https://api.nodexeus.io'
          NEXT_PUBLIC_MQTT_USERNAME: 'nodexeus'
          NEXT_PUBLIC_MQTT_PASSWORD: ${{ secrets.MQTT_PASSWORD }}
          NEXT_PUBLIC_MQTT_URL: 'wss://mqtt.nodexeus.io:8084/mqtt'
          NEXT_PUBLIC_VERCEL_ENV: 'production'
          NEXT_PUBLIC_LOADING_DURATION: '200'
          NEXT_PUBLIC_STRIPE_KEY: ${{ secrets.STRIPE_KEY }}
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            nodexeus/bv-web:latest
            nodexeus/bv-web:${{ steps.date.outputs.date }}
          cache-from: type=registry,ref=nodexeus/bv-web:latest
          cache-to: type=inline
