name: Web Build and Push

on:
  push:
    branches: [develop]
  workflow_dispatch:

jobs:
  build-and-push-development:
    runs-on: web
    environment: development

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            nodexeus/bv-web-dev:latest
            nodexeus/bv-web-dev:${{ steps.date.outputs.date }}
          build-args: |
            NEXT_PUBLIC_API_URL=${{ secrets.API_URL }}
            NEXT_PUBLIC_MQTT_URL=${{ secrets.MQTT_URL }}
            NEXT_PUBLIC_VERCEL_ENV=production
            NEXT_PUBLIC_LOADING_DURATION=200
            NEXT_PUBLIC_STRIPE_KEY=${{ secrets.STRIPE_KEY }}
          cache-from: type=registry,ref=nodexeus/bv-web-dev:latest
          cache-to: type=inline

  build-and-push-production:
    runs-on: web
    environment: production

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            nodexeus/bv-web:latest
            nodexeus/bv-web:${{ steps.date.outputs.date }}
          build-args: |
            NEXT_PUBLIC_API_URL=${{ secrets.API_URL }}
            NEXT_PUBLIC_MQTT_URL=${{ secrets.MQTT_URL }}
            NEXT_PUBLIC_VERCEL_ENV=production
            NEXT_PUBLIC_LOADING_DURATION=200
            NEXT_PUBLIC_STRIPE_KEY=${{ secrets.STRIPE_KEY }}
          cache-from: type=registry,ref=nodexeus/bv-web:latest
          cache-to: type=inline
