name: Set Secrets

on:
  workflow_dispatch:

jobs:
  build-and-push-production:
    runs-on: web
    environment: production

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT

      - name: Get short SHA
        id: sha
        run: echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile-secrets
          push: false
          tags: |
            nodexeus/bv-web-secrets:latest
            nodexeus/bv-web-secrets:${{ steps.date.outputs.date }}
          build-args: |
            NEXT_PUBLIC_API_URL=${{ secrets.API_URL }}
            NEXT_PUBLIC_MQTT_URL=${{ secrets.MQTT_URL }}
            NEXT_PUBLIC_VERCEL_ENV=production
            NEXT_PUBLIC_LOADING_DURATION=200
            NEXT_PUBLIC_STRIPE_KEY=${{ secrets.STRIPE_KEY }}
            NEXT_PUBLIC_SHORT_SHA=${{ steps.sha.outputs.sha }}
